//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslatedValueApi.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReturnCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReturnCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslatedValueApi.Domain.Resources.ReturnCodes", typeof(ReturnCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çeviri eklenirken hata ile karşılaşıldı..
        /// </summary>
        public static string EnglishTest_AddedTranslationsError {
            get {
                return ResourceManager.GetString("EnglishTest.AddedTranslationsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çeviri başarıyla eklendi..
        /// </summary>
        public static string EnglishTest_AddedTranslationsSuccessfully {
            get {
                return ResourceManager.GetString("EnglishTest.AddedTranslationsSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çeviri silinirken hata ile karşılaşıldı..
        /// </summary>
        public static string EnglishTest_DeletedTranslationsError {
            get {
                return ResourceManager.GetString("EnglishTest.DeletedTranslationsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çeviri başarıyla silindi..
        /// </summary>
        public static string EnglishTest_DeletedTranslationsSuccessfully {
            get {
                return ResourceManager.GetString("EnglishTest.DeletedTranslationsSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çeviri getirilirken hata ile karşılaşıldı..
        /// </summary>
        public static string EnglishTest_ReturnedTranslationsError {
            get {
                return ResourceManager.GetString("EnglishTest.ReturnedTranslationsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çeviri başarılı bir şekilde getirildi..
        /// </summary>
        public static string EnglishTest_ReturnedTranslationsSuccessfully {
            get {
                return ResourceManager.GetString("EnglishTest.ReturnedTranslationsSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çeviri güncelleme işleminde hata ile karşılaşıldı..
        /// </summary>
        public static string EnglishTest_UpdatedTranslationsError {
            get {
                return ResourceManager.GetString("EnglishTest.UpdatedTranslationsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çeviri güncelleme işlemi başarılı..
        /// </summary>
        public static string EnglishTest_UpdatedTranslationsSuccessfully {
            get {
                return ResourceManager.GetString("EnglishTest.UpdatedTranslationsSuccessfully", resourceCulture);
            }
        }
    }
}
