//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordApi.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReturnCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReturnCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordApi.Domain.Resources.ReturnCodes", typeof(ReturnCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelime eklerken hata ile karşılaşıldı..
        /// </summary>
        public static string EnglishTest_AddedWordError {
            get {
                return ResourceManager.GetString("EnglishTest.AddedWordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelime ekleme işlemi başarılı..
        /// </summary>
        public static string EnglishTest_AddedWordSuccessFully {
            get {
                return ResourceManager.GetString("EnglishTest.AddedWordSuccessFully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelime silinirken hata ile karşılaşıldı..
        /// </summary>
        public static string EnglishTest_DeletedWordError {
            get {
                return ResourceManager.GetString("EnglishTest.DeletedWordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelime başarıyla silindi..
        /// </summary>
        public static string EnglishTest_DeletedWordSuccessFully {
            get {
                return ResourceManager.GetString("EnglishTest.DeletedWordSuccessFully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelime getirilirken hata ile karşılaşıldı..
        /// </summary>
        public static string EnglishTest_ReturnedWordError {
            get {
                return ResourceManager.GetString("EnglishTest.ReturnedWordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelime getirme işlemi başarılı..
        /// </summary>
        public static string EnglishTest_ReturnedWordSuccessFully {
            get {
                return ResourceManager.GetString("EnglishTest.ReturnedWordSuccessFully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelime güncelleme işlemi başarılı..
        /// </summary>
        public static string EnglishTest_UpdatedWordSuccessFully {
            get {
                return ResourceManager.GetString("EnglishTest.UpdatedWordSuccessFully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelime gümcellenirken hata ile karşılaşıldı..
        /// </summary>
        public static string String1EnglishTest_UpdatedWordError {
            get {
                return ResourceManager.GetString("String1EnglishTest.UpdatedWordError", resourceCulture);
            }
        }
    }
}
